variables:
  - name: runCodesignValidationInjectionBG
    value: false
  - name: EnablePipelineCache
    value: true
  - ${{ if eq(parameters.enableMsBuildCaching, true) }}:
    - name: EnablePipelineCache
      value: true

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: enableMsBuildCaching
    type: boolean
    default: false
  - name: runTests
    type: boolean
    default: true
  - name: useVSPreview
    type: boolean
    default: false
  - name: useLatestWebView2
    type: boolean
    default: false
  - name: useLatestWinAppSDK
    type: boolean
    default: false
  - name: winAppSDKVersionNumber
    type: string
    default: 1.6
  - name: useExperimentalVersion
    type: boolean
    default: false

stages:
  # Allow manual builds to skip pre-check
  - ${{ if ne(variables['Build.Reason'], 'Manual') }}:
    - stage: Precheck
      jobs:
        - template: job-ci-precheck.yml

  - ${{ each platform in parameters.buildPlatforms }}:
    - stage: Test_${{ platform }}
      displayName: Test ${{ platform }}
      jobs:
        - template: job-test-project.yml
          parameters:
            platform: ${{ platform }}
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
