trigger:
  batch: true
  branches:
    include:
      - main
      - stable
#  paths:
#    exclude:
#      - doc/*
#      - temp/*
#      - tools/*
#      - '**.md'

pr:
  branches:
    include:
      - main
      - stable
#  paths:
#    exclude:
#      - '**.md'
#      - doc

name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: enableMsBuildCaching
    type: boolean
    displayName: "Enable MSBuild Caching"
    default: false
  - name: runTests
    type: boolean
    displayName: "Run Tests"
    default: true
  - name: useVSPreview
    type: boolean
    displayName: "Build Using Visual Studio Preview"
    default: false

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download WindowsAppSDK'
  inputs:
    buildType: 'specific'
    project: '55e8140e-57ac-4e5f-8f9c-c7c15b51929d'
    definition: '104083'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/release/1.8-stable'
    artifactName: 'WindowsAppSDK_Nuget_And_MSIX'
    targetPath: '$(Build.SourcesDirectory)\localpackages'
