pr: none
trigger: none

pool:
  vmImage: windows-latest

jobs:
- job: DownloadLocalizationFiles
  displayName: Download Localization Files
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    submodules: false
    fetchDepth: 1 # Don't need a deep checkout for loc files!
    persistCredentials: true

  - task: TouchdownBuildTask@3
    displayName: 'Download Localization Files -- PowerToys 37400'
    inputs:
      teamId: 37400
      TDBuildServiceConnection: $(TouchdownServiceConnection)
      authType: SubjectNameIssuer
      resourceFilePath: |
       **\Resources.resx
       **\Resource.resx
       **\Resources.resw
      appendRelativeDir: true
      localizationTarget: false

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Localization Files'
    inputs:
      targetPath: '$(Build.SourcesDirectory)'
      artifactName: 'localization-files'
      publishLocation: 'pipeline'